### ISSUE TITLE
Compatibilty issue with latest version (1.8.0) of i18next

### ISSUE THREAD

**Issue by julien51** [i18next/ng-i18next#83]
We just updated to @i18next version 1.8.0 and now we get errors:

```
TypeError: Cannot read property 'init' of undefined
	    at init (/Users/julien/repos/subtome.com/app/bower_components/ng-i18next/dist/ng-i18next.js:20:15)
	    at self.$get (/Users/julien/repos/subtome.com/app/bower_components/ng-i18next/dist/ng-i18next.js:81:3)
	    at Object.invoke (/Users/julien/repos/subtome.com/app/bower_components/angular/angular.js:3697:17)
```

Any idea what's going on?

**Comment by archer96** [comment]
I tested it with the latest version of `i18next` (1.9.0) and `ng-i18next` (v0.3.6) and it works.
Have you found a solution for your issue? :)

Regards,
Andre

**Comment by anwalkers** [comment]
Now compatible with the latest version of i18next
